feat(core): add humanName general FHIR type
bonfhir/bonfhir1_archive pull request #105
Opened 2023-02-17 14:56 UTC by ngouy

## What is this about

add new type formatters

2023-02-20 21:41 UTC, ngouy commented
@julienblin I will rebase the lodash things once your PR got merged

About the identifiers, I'm really not sure.
What's your take on it ?
https://github.com/bonfhir/bonfhir/pull/105/files#diff-9c2a583a7bd796347546fdfb9fbb475b3210ed4ba51d39fc16a39eea9718637bR61-R65

2023-02-21 13:08 UTC, julienblin requested changes
We need to review together the specs for those.

2023-02-21 13:08 UTC, julienblin commented on packages/core/r4b/data-types/address.ts
> +          return fhirAddress.text || "";
I think this should return "full" if `address.text` is missing. A fallback is a better solution IMHO.

2023-02-21 13:08 UTC, julienblin commented on packages/core/r4b/data-types/address.ts
> +export type FhirAddressFormatOptions = {
I believe we should include a `defaultCountry` option that would be used if the country is missing in the address data.

2023-02-21 13:08 UTC, julienblin commented on packages/core/r4b/data-types/address.ts
> +const addressUseOrder = {
This should be an option

2023-02-21 13:08 UTC, julienblin commented on packages/core/r4b/data-types/address.ts
> +};
Also, when passing an array, we should be given the option to display a single address (first determine by the order), or all of them

2023-02-21 13:08 UTC, julienblin commented on packages/core/r4b/data-types/address.ts
> +            ]).join("\n")
We should provide the option to format as a single line, or a paragraph

2023-02-21 13:08 UTC, julienblin commented on packages/core/r4b/data-types/address.ts
> +  ): string[] | string;
I believe format should always return `string`, not `string[]`

2023-02-21 13:08 UTC, julienblin commented on packages/core/r4b/data-types/address.ts
> +        return sortAddresses(fhirAddress).map(
This does not feel right. It format should always return a string IMHO.
We could leverage [Intl.ListFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/ListFormat)

2023-02-21 13:08 UTC, julienblin commented on packages/core/r4b/data-types/address.ts
> +    }
This feels like a `HasPeriodSorter` kinda helper

2023-02-21 14:52 UTC, ngouy commented on packages/core/r4b/data-types/address.ts
> +};
interesting
will do that

2023-02-21 14:52 UTC, ngouy commented on packages/core/r4b/data-types/address.ts
> +const addressUseOrder = {
Option + this one as default?
Will do

2023-03-01 16:57 UTC, julienblin approved these changes

2023-03-01 17:39 UTC, merged