175-Add a pattern option to the identifier data type adapter
bonfhir/bonfhir1_archive pull request #199
Opened 2023-04-25 22:31 UTC by jadiaheno

## What is this about

A `pattern` control was added to the options object of the `fhirIdentifierTypeAdapter.format()` function. This pattern control was added to support mandatory display formats of FHIR identifiers. 

The supported values are:
- a string: `999-9*9-aaaa`
- a map: `{ "https://fhir.nhs.uk/Id/nhs-number": "999 999 9999" }`
- a boolean: `true` for default formatting

The default format characters are:
- `9` for numbers
- `a` for letters
- `*` for numbers and letters
Any other character will be used as a template.

The formatting function can be reused and is in utils.
<img width="642" alt="image" src="https://user-images.githubusercontent.com/13062328/234417190-0c98e7b2-3545-4fd8-ac97-6f504635d590.png">

## Issue ticket numbers

#175 

## How can this be tested?

`yarn run test`

## Known limitations/edge cases

As of right now, the formatting is `at best`. It provides flexibility for custom patterning. Some limitations can be introduced  if we want to reject patterns (returning the original value)

<img width="544" alt="image" src="https://user-images.githubusercontent.com/13062328/234418333-78c51eb3-dcf9-403f-8994-497d48baa9a7.png">

2023-04-26 13:47 UTC, julienblin requested changes
This is great. A couple of changes though:

- default patterns should apply by default; settings to false disable patterns if need be
- we should be able to set a different set of default patterns for a specific instance of an adapter, same as `systemsLabels` on the constructor
- we should handle properly the case of having the source value already formatted correctly (see missing test case)
- we should be able to escape pattern characters to use them in the output string if need be

Maybe we could simplify the pattern by only using `#` as a placeholder? We don't care about validating the values, just formatting them.

So what about using only `#` as a placeholder, and having the possibility to use `\#` to output `#` in the final pattern?

2023-04-26 13:47 UTC, julienblin commented on packages/core/r4b/data-types/identifier.test.ts
> +  });
This test does not pass at the moment:

```typescript
it("does nothing if already formatted", () => {
      const identifier: Identifier = {
        system: "http://hl7.org/fhir/sid/us-ssn",
        value: "753-59-831",
      };
      expect(
        fhirIdentifierTypeAdapter().format(identifier, {
          pattern: true,
          style: "value",
        })
      ).toEqual("753-59-831");
    });
```

2023-04-26 13:47 UTC, julienblin commented on packages/core/r4b/data-types/identifier.ts
> +  pattern?: string | Record<string, string> | boolean | null | undefined;
By default it should format using the default patterns.
I would suggest only accepting `false` as a value to disable the default patterns.


```suggestion
  pattern?: string | Record<string, string> | false | null | undefined;
```

2023-04-26 13:47 UTC, julienblin commented on packages/core/r4b/utils.ts
> +const defaultFormatChars: { [key: string]: RegExp } = Object.freeze({
How can we escape does characters so that we can use it in the output (instead of a placeholder)?

2023-04-26 13:47 UTC, julienblin commented on packages/core/r4b/data-types/identifier.ts
> +};
We should remove the Canadian SIN as it's not part of the official spec.
```suggestion
export const DEFAULT_SYSTEMS_PATTERNS: Required<Record<string, string>> = {
  "http://hl7.org/fhir/sid/us-ssn": "999-99-999",
  "http://hl7.org/fhir/sid/us-mbi": "9a*9-a*9-aa99",
};
```

2023-04-26 13:47 UTC, julienblin commented on packages/core/r4b/data-types/identifier.ts
>  export interface FhirIdentifierTypeAdapter {
We should accept a global pattern map, the same way we do with `systemsLabels`, so that the default can be overriden globally on a specific adapter instance.

2023-04-28 10:01 UTC, jadiaheno commented on packages/core/r4b/data-types/identifier.ts
> +  pattern?: string | Record<string, string> | boolean | null | undefined;
Default formatting using the default patterns would be a breaking change of the format function?

2023-04-28 11:54 UTC, julienblin commented on packages/core/r4b/data-types/identifier.ts
> +  pattern?: string | Record<string, string> | boolean | null | undefined;
Yes. In this case it's OK though, the impact is minimal and we are still in alpha :-)

2023-04-28 13:44 UTC, jadiaheno commented on packages/core/r4b/utils.ts
> +const defaultFormatChars: { [key: string]: RegExp } = Object.freeze({
Per recommendation, escaping with `\`.

2023-04-28 15:46 UTC, jadiaheno commented on packages/core/r4b/data-types/identifier.test.ts
> +  });
Added.

2023-04-28 15:46 UTC, jadiaheno commented on packages/core/r4b/data-types/identifier.ts
> +};
CA SIN removed.

2023-04-28 15:47 UTC, jadiaheno commented on packages/core/r4b/data-types/identifier.ts
>  export interface FhirIdentifierTypeAdapter {
`systemsPatterns` added.

2023-04-28 15:48 UTC, jadiaheno commented
I don't have any further comments at this time. Once the PR is ready to be merged, I'll make sure to rebase it accordingly.

2023-04-28 19:30 UTC, julienblin requested changes
This is great - thanks for the fixes!

I have one last request related to https://bonfhir.dev/contributing/contributing#conventional-commits

Can you please merge all this, rebase and create a single nice conventional commit?
The reason is we use this to generate changelogs, so a nice clean one is important.
The rest is great, exactly what we need - thank you!

2023-05-01 10:03 UTC, jadiaheno commented
The changes were squashed into a single commit.

2023-05-01 11:48 UTC, julienblin approved these changes
LGTM 🎉

2023-05-01 20:33 UTC, merged