style: add note to autogenerated files
bonfhir/bonfhir1_archive pull request #54
Opened 2023-02-03 20:41 UTC by ngouy

## What is this about
Add a note to autogenerated file so we know wich file to look at if some updates need to happens

2023-02-03 20:42 UTC, ngouy commented
Happy to update the note content if this one isn't good enought

2023-02-06 17:56 UTC, julienblin requested changes
This is the final result we want to obtain - great!

However, I feel it would be better implemented as a feature of the code generator. e.g.

```bash
codegen --file-header "..."
```

This value could accept a `{template}` token that would be substituted with the template file path.

Files are written [here](https://github.com/bonfhir/bonfhir/blob/d4912c196d4d95b24404856f8b1d9aac313d978b/packages/codegen/src/commands/run/process-templates.ts#L75), and [here also](https://github.com/bonfhir/bonfhir/blob/d4912c196d4d95b24404856f8b1d9aac313d978b/packages/codegen/src/commands/run/helpers/writeFiles.ts#L19)

We could have a default file header if no value is provided:

```typescript
/**
 * NOTE: This file is code generated.
 *
 * Do not edit this file manually.
 * Instead, edit the template file '{template}'
 */
```

2023-02-08 10:23 UTC, julienblin requested changes

2023-02-08 10:23 UTC, julienblin commented on packages/codegen/src/commands/run/process-templates.ts
> +  );
Be careful with this, as `__dirname` is a reserved keyword in CommonJS: https://nodejs.org/api/modules.html#__dirname

Also, including the template this way will complicate bundling (as we don't bundle `.hbs` files by default).
I would suggest having the default template as a typescript file that export the template as string. Easier and more reliable.

2023-02-08 10:23 UTC, julienblin commented on packages/codegen/src/commands/run/autogenerated-note.hbs
> +
Let's use the name of the package instead.

```suggestion
/**
 * NOTE: This file is auto generated by the `@bonfhir/codegen` code generator program.
 *
 * Do not edit this file manually.
 * Instead, edit {{templatePath}}
 *
 */

```

2023-02-08 16:48 UTC, ngouy commented on packages/codegen/src/commands/run/process-templates.ts
> +  );
the first part I get, not the second one

It was quite a headache for me to understand:
1 - where to put the file 
2 - how to import it

If that's ok I think it will be easier to pear finish this one

2023-02-08 21:45 UTC, merged