feat: add bundleResources helper method to bundle navigator
bonfhir/bonfhir1_archive pull request #55
Opened 2023-02-03 21:19 UTC by ngouy

## What is this about

Add a new helper to grab all the resources of a bundler at once

## Issue ticket numbers

#48 

## How can this be tested?

Not sure

## Known limitations/edge cases

- Unsorted array
- should we push the resource to the array only if the resource has an id?

2023-02-03 21:20 UTC, ngouy commented on packages/core/r4b/bundle-navigator.ts
>              this._resourcesByRelativeReference.set(
should this line be encapsulated in the id part @julienblin?

2023-02-06 17:47 UTC, julienblin requested changes

2023-02-06 17:47 UTC, julienblin commented on packages/core/r4b/bundle-navigator.ts
>              this._resourcesByRelativeReference.set(
I think this is fine, as we won't mandate an id in this index.
Let's keep this straightforward :-)

2023-02-06 17:47 UTC, julienblin commented on packages/core/r4b/bundle-navigator.ts
> +      this._bundleResources = [];
Since the bundle navigator allows navigating a set of multiple bundles, we should ensure uniqueness of resources across bundles.
One easy way to do so is to make is a `Map<[ResourceType, string], PrimaryResourceType | SecondaryResourceType>` so that we de-duplicate on resource type + id.

2023-02-06 17:47 UTC, julienblin commented on packages/core/r4b/bundle-navigator.ts
> +  public bundleResources() {
I think making this a [getter](https://www.typescriptlang.org/docs/handbook/2/classes.html#getters--setters) might make the API more fluid:

```suggestion
  public get resources() {
```

Example usage:

```typescript
navigator.resources.map(res => ...);
```

2023-02-06 21:15 UTC, ngouy commented on packages/core/r4b/bundle-navigator.ts
>              this._resourcesByRelativeReference.set(
But how do we mark the unicity of id-less resources in the map suggested above?

2023-02-10 12:42 UTC, julienblin commented
In the end, we could simply re-use the already existing index named `_resourcesByRelativeReference` :-)

2023-02-10 12:49 UTC, merged

2023-02-10 13:00 UTC, ngouy commented
so we only have resources that have an ID
Which is fine I guess. It probably woul've been complicated to have unicity in order to avoid duplicates for id-less resources