feat(ui-components): introduce primitive-data type: date
bonfhir/bonfhir1_archive pull request #65
Opened 2023-02-07 15:42 UTC by ngouy

## What is this about

Introduce new primitive data type: date
Also introduce:
- formatter concept (+ related provider)
- a baseFormatter

## Issue ticket numbers

https://github.com/bonfhir/bonfhir/issues/63

## How can this be tested?

TBD

Please describe how these changes have been tested, and how can they be tested by the reviewer.
Include any relevant context information (e.g., usernames, resource IDs, …) that can make it faster for the reviewer to test it.

2023-02-07 16:24 UTC, julienblin requested changes
This is great!
I thought about it more and I believe we should provide a default formatter that uses the standard `Intl` API as much as possible.

Also, introducing some options into the component and formatter (e.g. the `dateStyle`) will allow for more versatility in usage.

Hit me up if this is not clear!

2023-02-07 16:24 UTC, julienblin commented on packages/ui-components/r4b/FhirUIComponentsContext.tsx
> +  formatDate: (date: FhirDate) => string;
This may take an optional `dateStyle` parameter
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/DateTimeFormat#dateStyle

2023-02-07 16:24 UTC, julienblin commented on packages/ui-components/r4b/data-types/primitive-types/FhirDateValue.tsx
>  export interface FhirDateValueProps {
This may take an optional dateStyle parameter - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/DateTimeFormat#dateStyle

Should default to short

2023-02-07 16:24 UTC, julienblin commented on packages/ui-components/r4b/FhirUIComponentsProviders/FhirUIComponentsBaseFormatter.tsx
> +export const FhirUIComponentsBaseFormatter =
This is the right idea.
However, I would suggest we use the default [Intl API](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl).
So we would create a `FhirUIComponentsIntlFormatter` that take an optional locale as a constructor parameter.

We will need proper encapsulation to also handle the partial dates use case...

2023-02-07 18:04 UTC, ngouy commented on packages/ui-components/r4b/FhirUIComponentsContext.tsx
> +  formatDate: (date: FhirDate) => string;
takes a locale, if not provided, it takes the one from browser

2023-02-14 13:00 UTC, julienblin commented
@ngouy - I feel like we should close this PR, as it's been superseded by others: #87, #81

2023-02-20 15:44 UTC, closed without merging