feat(core): introduce decimal type fhir adapter
bonfhir/bonfhir1_archive pull request #74
Opened 2023-02-08 20:22 UTC by ngouy

## What is this about

Introduce adapter for the [fhir decimal type](https://hl7.org/fhir/datatypes.html#decimal)

2023-02-08 21:01 UTC, julienblin requested changes
Let's discuss when you have some time

2023-02-08 21:01 UTC, julienblin commented on packages/core/r4b/data-types/decimal.ts
> +  Intl.DateTimeFormat(locale);
Nitpicking...
```suggestion
  Intl.NumberFormat(locale);
```

2023-02-08 21:01 UTC, julienblin commented on packages/core/r4b/data-types/decimal.ts
> +      if (value.includes(".")) return parseFloat(value);
We may run into issues related to precision here, specifically with those horrible IEEE754 floats.
Maybe we should parse it into https://mikemcl.github.io/decimal.js/?

2023-02-10 01:32 UTC, ngouy commented on packages/core/r4b/data-types/date.ts
> +      return new Intl.DateTimeFormat(locale, options).format(fhirDate.date);
@julienblin it was on my stash

I can roll it back

Which way should we favor?

2023-02-10 19:08 UTC, julienblin approved these changes
LGTM! - I will just squash the commits and merge (to avoid too much noise on Changelog).

Thank you! 🙏

2023-02-10 19:12 UTC, julienblin commented on packages/core/r4b/data-types/date.ts
> +      return new Intl.DateTimeFormat(locale, options).format(fhirDate.date);
We'll keep your version :-)

2023-02-10 19:23 UTC, merged