feat(core): add adapter for boolean primitive data type
bonfhir/bonfhir1_archive pull request #76
Opened 2023-02-09 14:13 UTC by ngouy

## What is this about
Introduce boolean primitive data type  adapter

2023-02-10 13:13 UTC, julienblin requested changes
A few nitpicks.

Also for options, just a quick remark: I believe `null` and `undefined` are semantically equivalent for a formatter, so we could group `null` and `undefined` labels as `nil`.

2023-02-10 13:13 UTC, julienblin commented on packages/core/r4b/data-types/boolean.ts
> +          "Value does not match the fhir boolean format as described in `https://hl7.org/fhir/datatypes.html#boolean'"
```suggestion
          "Value does not match the fhir boolean format as described in `https://hl7.org/fhir/datatypes.html#boolean`
```

2023-02-10 13:13 UTC, julienblin commented on packages/core/r4b/data-types/boolean.ts
> +      }
Javascript is happy to coerce strings when using templates :-) 

```suggestion
      return labels[`${fhirBoolean}`];
```

2023-02-10 13:13 UTC, julienblin commented on packages/core/r4b/data-types/boolean.ts
> +import { merge } from "lodash";
This one is tricky - lodash is not an esm module, so to ensure compatiblity you need to import it from the root only.

```suggestion
import _ from "lodash";
```

2023-02-10 13:13 UTC, julienblin commented on packages/core/r4b/data-types/boolean.ts
> +      const labels = merge({}, defaultLabels, options.labels || {});
```suggestion
      const labels = _.merge({}, defaultLabels, options.labels || {});
```

2023-02-10 13:13 UTC, julienblin commented on packages/core/r4b/data-types/boolean.ts
> +    undefined?: string;
Generally, `null` and `undefined` are functionally equivalent.
So we could group them as `nil` to make it easier?

```suggestion
    nil?: string;
```

2023-02-10 15:28 UTC, ngouy commented on packages/core/r4b/data-types/boolean.ts
> +      }
ho Not sure if TS will be happy

I was using `String(fhirBoolean)` and he was not happy

2023-02-14 14:04 UTC, ngouy commented
@julienblin that would be the last one of the primitives types

2023-02-15 13:58 UTC, julienblin approved these changes
LGTM!

Sorry for the delay - I was looking at a stale version of the branch, so I was not looking at your latest changes.

2023-02-16 14:20 UTC, merged